source 'https://github.com/RedP4nda/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!


target 'RPFramework_Example' do
  pod 'RPFramework', :path => '../'

  target 'RPFramework_Tests' do
    inherit! :search_paths
  end

end
