  podspec: RPFramework.podspec
  author: MrCloud
  author_url: https://github.com/RedP4nda
  github_url: https://github.com/RedP4nda/RPFramework
  theme: fullwidth                                     
